# Generated by Django 2.0.7 on 2018-08-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=90, verbose_name='タイトル')),
                ('data_str', models.CharField(max_length=10000, null=True, verbose_name='データ(文字型)')),
                ('data_date', models.DateField(null=True, verbose_name='データ(日時)')),
                ('data_datetime', models.DateTimeField(null=True, verbose_name='データ(日時)')),
                ('data_bool', models.BooleanField(default=False, verbose_name='データ(チェックボックス)')),
                ('data_choice', models.CharField(blank=True, choices=[('OBJ1', '選択肢1'), ('OBJ2', '選択肢2'), ('OBJ3', '選択肢3')], max_length=10, null=True, verbose_name='データ(セレクトボックス)')),
            ],
        ),
    ]
